/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/edit-header copy 2.vue')['default']
    3: typeof import('./src/components/edit-header copy 3.vue')['default']
    copy: typeof import('./src/components/edit-header copy.vue')['default']
    EditBlock: typeof import('./src/components/edit/edit-block.vue')['default']
    EditConfig: typeof import('./src/components/edit/edit-config.vue')['default']
    EditHeader: typeof import('./src/components/edit/edit-header.vue')['default']
    EditRender: typeof import('./src/components/edit/edit-render.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
